CREATE TABLE [dbo].[Role]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(200) NOT NULL, 
    [IsActive] BIT NOT NULL DEFAULT 1, 
    [CreatedBy] NVARCHAR(50) NOT NULL, 
    [CreatedDate] DATETIME NOT NULL DEFAULT GETUTCDATE(), 
    [ModifiedBy] NVARCHAR(50) NOT NULL, 
    [ModifiedDate] DATETIME NOT NULL DEFAULT GETUTCDATE()
)
